version: '3.0'

volumes:
  wdisk:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './webdiskdata'

services:
  backend.webdisk.com:
    image: whatyoudo/webdisk:1.0.0
    volumes:
      - wdisk:/disk

  nginx.webdisk.com:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 5080:80

